-- 동사로 푸는 수학 — 최초 스키마
--
-- 엔티티에서 뽑아낸 DDL 을 손본 것이다. 앞으로 스키마는 이 폴더의 파일로만 바꾼다.
-- (ddl-auto 는 validate 로 두어, 엔티티와 이 파일이 어긋나면 서버가 아예 뜨지 않는다.)
--
-- enum 값에 CHECK 제약을 걸지 않았다. 문제 유형을 하나 늘릴 때마다 마이그레이션을 쓰게 되기 때문이다.
-- 값의 유효성은 애플리케이션에서 지킨다.

-- ── 학원과 사람 ──────────────────────────────────────────────

create table academy (
    id          bigint generated by default as identity primary key,
    name        varchar(60) not null,
    code        varchar(6)  not null,
    created_at  timestamp(6) with time zone,
    updated_at  timestamp(6) with time zone,
    constraint uk_academy_code unique (code)
);

create table teacher (
    id             bigint generated by default as identity primary key,
    academy_id     bigint       not null,
    email          varchar(120) not null,
    password_hash  varchar(100) not null,
    name           varchar(30)  not null,
    role           varchar(10)  not null,
    active         boolean      not null,
    created_at     timestamp(6) with time zone,
    updated_at     timestamp(6) with time zone,
    constraint uk_teacher_email unique (email),
    constraint fk_teacher_academy foreign key (academy_id) references academy (id)
);

create index ix_teacher_academy on teacher (academy_id);

create table classroom (
    id          bigint generated by default as identity primary key,
    academy_id  bigint      not null,
    name        varchar(40) not null,
    grade       integer,
    created_at  timestamp(6) with time zone,
    updated_at  timestamp(6) with time zone,
    constraint fk_classroom_academy foreign key (academy_id) references academy (id)
);

create index ix_classroom_academy on classroom (academy_id);

create table student (
    id            bigint generated by default as identity primary key,
    academy_id    bigint       not null,
    classroom_id  bigint,
    name          varchar(30)  not null,
    pin_hash      varchar(100) not null,
    grade         integer      not null,
    active        boolean      not null,
    created_at    timestamp(6) with time zone,
    updated_at    timestamp(6) with time zone,
    constraint fk_student_academy foreign key (academy_id) references academy (id),
    -- 반을 지워도 아이는 남는다
    constraint fk_student_classroom foreign key (classroom_id) references classroom (id) on delete set null
);

-- 학생 로그인은 (학원, 이름) 으로 후보를 찾은 뒤 PIN 으로 가린다
create index ix_student_academy_name on student (academy_id, name);

-- ── 문제 템플릿 ──────────────────────────────────────────────

create table problem_template (
    id               bigint generated by default as identity primary key,
    code             varchar(20)  not null,
    category         varchar(20)  not null,
    operation        varchar(20)  not null,
    number_pattern   varchar(20)  not null,
    pattern          varchar(600) not null,
    unit             varchar(10)  not null,
    min_grade        integer      not null,
    max_grade        integer      not null,
    second_scale     integer      not null,
    needs_two_names  boolean      not null,
    constraint uk_template_code unique (code)
);

create table problem_template_cue (
    template_id  bigint      not null,
    word         varchar(40) not null,
    constraint fk_cue_template foreign key (template_id) references problem_template (id) on delete cascade
);

create index ix_cue_template on problem_template_cue (template_id);

-- ── 과제와 채점 ──────────────────────────────────────────────

create table assignment (
    id                 bigint generated by default as identity primary key,
    academy_id         bigint      not null,
    classroom_id       bigint,
    created_by         bigint      not null,
    title              varchar(80) not null,
    grade              integer     not null,
    problem_count      integer     not null,
    carry              boolean     not null,
    -- 문제를 저장하지 않고 이 씨앗으로 매번 다시 만든다
    seed               bigint      not null,
    same_for_everyone  boolean     not null,
    due_at             timestamp(6) with time zone,
    closed_at          timestamp(6) with time zone,
    created_at         timestamp(6) with time zone,
    updated_at         timestamp(6) with time zone,
    constraint fk_assignment_academy foreign key (academy_id) references academy (id),
    constraint fk_assignment_classroom foreign key (classroom_id) references classroom (id) on delete set null,
    constraint fk_assignment_teacher foreign key (created_by) references teacher (id)
);

create index ix_assignment_academy on assignment (academy_id, id);
create index ix_assignment_classroom on assignment (classroom_id);

create table assignment_category (
    assignment_id  bigint      not null,
    category       varchar(20) not null,
    constraint fk_assignment_category foreign key (assignment_id) references assignment (id) on delete cascade
);

create index ix_assignment_category on assignment_category (assignment_id);

create table student_assignment (
    id             bigint generated by default as identity primary key,
    assignment_id  bigint not null,
    student_id     bigint not null,
    -- 아이마다 다른 문제를 낼 때를 위해 씨앗을 따로 들고 있다
    seed           bigint not null,
    started_at     timestamp(6) with time zone,
    completed_at   timestamp(6) with time zone,
    created_at     timestamp(6) with time zone,
    updated_at     timestamp(6) with time zone,
    constraint uk_student_assignment unique (assignment_id, student_id),
    constraint fk_sa_assignment foreign key (assignment_id) references assignment (id) on delete cascade,
    constraint fk_sa_student foreign key (student_id) references student (id)
);

create index ix_student_assignment_student on student_assignment (student_id, id);

create table submission (
    id                     bigint generated by default as identity primary key,
    student_assignment_id  bigint       not null,
    problem_no             integer      not null,
    step                   varchar(12)  not null,
    submitted_value        varchar(120) not null,
    correct                boolean      not null,
    -- 리포트에서 유형별로 묶으려고 함께 저장한다 (매번 문제를 다시 만들지 않으려고)
    category               varchar(20)  not null,
    submitted_at           timestamp(6) with time zone not null,
    -- 한 단계는 한 번만. 끊겨서 다시 눌러도 점수가 바뀌지 않는 근거가 이 제약이다.
    constraint uk_submission_step unique (student_assignment_id, problem_no, step),
    constraint fk_submission_sa foreign key (student_assignment_id) references student_assignment (id) on delete cascade
);

create index ix_submission_sa on submission (student_assignment_id);
