-- 연산 게임 한 판의 기록.
--
-- 문제는 저장하지 않는다. 학습지와 같은 방식으로 씨앗만 두고 채점할 때 다시 만든다.
-- academy_id 는 student 를 타고 가면 알 수 있지만, 순위표를 테이블 하나로 뽑으려고 같이 둔다
-- (학생이 학원을 옮기는 일은 없으므로 어긋날 걱정이 없다).

create table game_round (
    id             bigint generated by default as identity primary key,
    student_id     bigint  not null,
    academy_id     bigint  not null,
    grade          integer not null,
    seed           bigint  not null,
    problem_count  integer not null,
    limit_seconds  integer not null,
    attempted      integer not null,
    solved         integer not null,
    elapsed_ms     integer,
    started_at     timestamp(6) with time zone not null,
    finished_at    timestamp(6) with time zone,
    constraint fk_game_student foreign key (student_id) references student (id),
    constraint fk_game_academy foreign key (academy_id) references academy (id)
);

-- 순위표: 학원 안에서 많이 맞힌 순, 같으면 빨리 끝낸 순
create index ix_game_ranking on game_round (academy_id, solved desc, elapsed_ms asc);
create index ix_game_student on game_round (student_id, id desc);
